name: Auto Check Lint
on:
  pull_request: 
    branches: ['main']

jobs: 
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          npm ci
          npm run lint
